export const types = {
  GET_EMPLOYEES: "GET_EMPLOYEES", //GET
  GET_EMPLOYEES_BY_ID: "GET_EMPLOYEES_BY_ID", //GET
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE", //POST
  UPDATE_EMPLOYEE_BY_ID: "UPDATE_EMPLOYEE_BY_ID", //PATCH
  DELETE_EMPLOYEE_BY_ID: "DELETE_EMPLOYEE_BY_ID", //DELETE
  ERROR_EMPLOYEES: "ERROR_EMPLOYEES",
};
